version: '3.1'

services:
  db:
    image: postgres:15.2
    restart: always
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_ROOT_USER
      - POSTGRES_PASSWORD=$DB_ROOT_PASSWORD
volumes:
  psql_data:
    driver: local